Þ•    1      ¤  C   ,      8  #   9  
   ]  y   h  	   â     ì  F   û  S   B  $   –  U   »       $   (  7   M  O   …     Õ     ò  #     	   3  ›   =  Ã   Ù  q        	     "	     3	  e   B	     ¨	  .   º	  *   é	  =   
     R
  %   p
     –
  /   ´
     ä
       *     -   6  j   d  I   Ï  ï        	
     
     6
  !   E
     g
  7   }
  $   µ
  #   Ú
     þ
  Ü    $   ë  
     –        µ     Â  R   Õ  f   (  '     j   ·     "  +   @  @   l  a   ­  $     &   4  -   [     ‰  Ÿ   –  ï   6  …   &     ¬     ¿     Ó  w   å     ]  8   s  4   ¬  P   á  4   2  (   g  $     3   µ  !   é       .     @   C  „   „  B   	  ø   L     E     X     p  ,   Š     ·  7   Í  /     3   5     i     )   +                        	      .                    #   -   $                                  ,            &   *       (                   /      
       0           '                 "                !   
   1             %        %s &#8220;%s&#8221; already exists. - Select - A new version of this importer is available. Please update to version %s to ensure compatibility with newer export files. All done. Assign Authors Choose a WXR (.xml) file to upload, then click Upload file and import. Details are shown above. The importer will now try again with a different parser... Download and import file attachments Failed to create new user for %s. Their posts will be attributed to the current user. Failed to import %s %s Failed to import %s &#8220;%s&#8221; Failed to import &#8220;%s&#8221;: Invalid post type %s Failed to import author %s. Their posts will be attributed to the current user. Failed to import category %s Failed to import post tag %s Fetching attachments is not enabled Have fun! Howdy! Upload your WordPress eXtended RSS (WXR) file and we&#8217;ll import the posts, pages, comments, custom fields, categories, and tags into this site. If a new user is created by WordPress, a new password will be randomly generated and the new user&#8217;s role will be set as %s. Manually changing the new user&#8217;s details will be necessary. Import <strong>posts, pages, comments, custom fields, categories, and tags</strong> from a WordPress export file. Import Attachments Import WordPress Import author: Import posts, pages, comments, custom fields, categories, tags and more from a WordPress export file. Invalid file type Menu item skipped due to invalid menu slug: %s Menu item skipped due to missing menu slug Remember to update the passwords and roles of imported users. Remote file is incorrect size Remote file is too large, limit is %s Remote server did not respond Remote server returned error response %1$d %2$s Sorry, there has been an error. Submit The file does not exist, please try again. There was an error when reading this WXR file This WXR file (version %s) may not be supported by this version of the importer. Please consider updating. This does not appear to be a WXR file, missing/invalid WXR version number To make it easier for you to edit and save the imported content, you may want to reassign the author of the imported item to an existing user of this site. For example, you may want to import all the entries as <code>admin</code>s entries. WordPress Importer Zero size file downloaded as a new user: assign posts to an existing user: http://wordpress.org/ http://wordpress.org/extend/plugins/wordpress-importer/ or assign posts to an existing user: or create new user with login name: wordpressdotorg Project-Id-Version: WordPress Importer 0.5
Report-Msgid-Bugs-To: http://wordpress.org/tag/wordpress-importer
POT-Creation-Date: 2011-07-16 15:45:12+00:00
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
PO-Revision-Date: 2014-08-09 15:11+0100
Last-Translator: Roland Lemminga <roland.lemminga@home.nl>
Language-Team: R. Lemminga <roland@robeliki.nl>
X-Generator: Poedit 1.6.7
Plural-Forms: nplurals=2; plural=(n != 1);
Language: nl_NL
 %s &#8220;%s&#8221; bestaat alreeds. - Selecteer - Een nieuwe versie van deze importeur beschikbaar. Gelieve te updaten naar versie %s om compatibiliteit te garanderen en met nieuwere export bestanden. Alles klaar. Toegewezen Auteurs Kies een WXR (.xml) bestand om te uploaden, klik op Bestand uploaden en importeer. Details worden hierboven getoond. De importeerfuctie zal nu opnieuw proberen met een andere parser ... Download en importeer bestand bijlages. Fout tijdens creÃ«ren nieuwe gebruiker voor %s. Hun posten zal worden toegewezen aan de huidige gebruiker. Fout tijdens importeren %s %s Fout tijdens importeren %s &#8220;%s&#8221; Fout tijdens importeren &#8220;%s&#8221;: Ongeldige post type %s Mislukt auteur %s te importeren. Hun posten zullen worden toegeschreven aan de huidige gebruiker. Fout tijdens importeren categorie %s Fout tijdens importeren bericht tag %s Het ophalen van bijlagen is niet ingeschakeld Heb plezier! Hallo! Upload uw WordPress eXtended RSS-bestand (WXR) en wij importeren de berichten, pagina's, reacties, aangepaste velden, categorieÃ«n en tags in deze site. Als er een nieuwe gebruiker wordt aangemaakt door WordPress, zal een nieuw wachtwoord worden willekeurig gegenereerd en de nieuwe user&#8217;s rol zal zijn als %s. Handmatig de gegevens van de nieuwe gebruiker te veranderen zal nodig zijn. Importeer <strong> berichten, pagina's, reacties, aangepaste velden, categorieÃ«n en tags </ strong> van een WordPress-exportbestand. Importeer Bijlagen Importeer Wordpress Importeer auteur: Importeer berichten, pagina's, reacties, aangepaste velden, categorieÃ«n, tags en meer van een WordPress exportbestand. Ongeldig bestandstype Menu-item overgeslagen vanwege ontbrekende menu slug: %s Menu-item overgeslagen vanwege ontbrekende menu slug Vergeet niet om de wachtwoorden en rollen van geÃ¯mporteerde gebruikers updaten. Extern bestand heeft niet de juiste bestands grootte Extern bestand is te groot, limiet is %s Externe server heeft niet gereageerd Externe server stuurde foutreactie  %1$d %2$s terug Sorry, er is een fout opgetreden. Verstuur Het bestand niet bestaat, probeer het opnieuw. Er is een fout opgetreden tijdens het lezen van deze WXR bestand Deze WXR bestand (versie %s) mogelijk niet ondersteund door deze versie van de importeer. U kunt het te overwegen om het te updaten. Dit lijkt geen WXR bestand, ontbrekende/ongeldige WXR versienummer Om het makkelijker voor u om te bewerken en de geÃ¯mporteerde inhoud te bewaren, kunt u de auteur van de ingevoerde post toewijzen aan een bestaande gebruiker van deze site. Bijvoorbeeld, kunt u alle importeren met  items als <code>admin</ code>s . WordPress Importer Leeg bestand gedownload als een nieuwe gebruiker: wijs posten toe aan een bestaande gebruiker: http://wordpress.org/ http://wordpress.org/extend/plugins/wordpress-importer/ of wijs posten toe aan een bestaande gebruiker: of creÃ«er een nieuwe gebruiker met gebruikersnaam: wordpressdotorg 
